### ISSUE TITLE
编辑wechatpay-apiv3没有Pre-request Scrip一栏

### ISSUE THREAD

**Issue by xingchunzhe111** [wechatpay-apiv3/wechatpay-postman-script#1]
(选中wechatpay-apiv3，右键Edit进入Collection的配置页面。在弹出的Edit Collection的浮层上部的多个分栏中)这里没有多个分栏，里面只有一个描述信息
如果是打开这个目录下面的单个对应的接口的话，里面是有Pre-request Scrip一栏的，但是打开后，里面是没有代码片段的？？？？？？？？？？？？？？？？

**Comment by xingchunzhe111** [comment]
[https://img1.vyicoo.cn/net-shop/Uploads/happy/2019/07/11/1562811948759.png](url)

**Comment by xy-peng** [comment]
请问你的postman是哪个版本？升级到最新版本的app试试

**Comment by zhimma** [comment]
![image](https://user-images.githubusercontent.com/13248107/62281163-db069a00-b47f-11e9-9725-2e943abe375a.png)
![image](https://user-images.githubusercontent.com/13248107/62281192-e6f25c00-b47f-11e9-9453-494e6fbb7d34.png)

没有文档描述的
```const private_key = `-----BEGIN PRIVATE KEY-----
-----END PRIVATE KEY-----`;
      
const mchid = "190000xxxx";
const serialNo = "yourserialno";
```

是需要自己加吗？

**Comment by xy-peng** [comment]
脚本的配置是在collection的Edit里面，我补一些图吧，也放到readme中。
<img width="1660" alt="postman1" src="https://user-images.githubusercontent.com/1812516/62339118-84e03800-b50d-11e9-92f3-aae11d7cc7ce.png">

然后在EDIT COLLECTION里面就能看到了
<img width="1660" alt="postman2" src="https://user-images.githubusercontent.com/1812516/62339418-88c08a00-b50e-11e9-9276-970068fb5af7.png">

最后一步是设置单个请求的头部
<img width="1660" alt="postman3" src="https://user-images.githubusercontent.com/1812516/62339751-b4903f80-b50f-11e9-8eb3-5538b26cdc8c.png">

**Comment by zhimma** [comment]
@xy-peng 
谢谢，看到了，确实是这样子，

我按照wechatpay-apiv3.postman_collection.json 这个文件中的内容，最后也生成了😢
