### ISSUE TITLE
导入脚本，配置全局变量后请求报错，希望可以支持下postman的全局变量

### ISSUE THREAD

**Issue by Memory-9527** [wechatpay-apiv3/wechatpay-postman-script#12]
<img width="886" alt="image" src="https://user-images.githubusercontent.com/30432849/195357856-3973e35d-ce78-4a48-bec4-a63e45ba09ee.png">
<img width="1223" alt="image" src="https://user-images.githubusercontent.com/30432849/195358069-24b40f5e-f690-4324-a71d-f3cc058ae1b3.png">

**Comment by xy-peng** [comment]
正好在重构这个脚本。你可以试下这段代码

```javascript
let sdk = require('postman-collection'),
    newRequest = new sdk.Request(pm.request.toJSON()),
    resolvedRequest = newRequest.toObjectResolved(null, [pm.variables.toObject()], { ignoreOwnVariables: true }),
    url = new sdk.Url(resolvedRequest.url),
    canonicalUrl = url.getPathWithQuery()

let method = request.method

var body = ""
if (method == 'POST' || method == 'PUT' || method == 'PATCH') {
    body = resolvedRequest.body.raw;
}
```

你也可以试试 [APIv3 Public Workspace](https://www.postman.com/wechatpay-dev/workspace/apiv3-public-workspace)，欢迎反馈。⚠️ workspace 的路径更改，请使用新链接。

PS：证书密钥在 Environment 中设置，不在脚本中设置了。

**Comment by Memory-9527** [comment]
好的，我研究下，有问题我继续反馈
