### ISSUE TITLE
使用脚本调用“检查子商户开票功能状态”接口报签名错误

### ISSUE THREAD

**Issue by Memory-9527** [wechatpay-apiv3/wechatpay-postman-script#14]
请求URL：https://api.mch.weixin.qq.com/v3/new-tax-control-fapiao/merchant/{sub_mchid}/check
Request-ID：08CBCAC49A0610E802189CABA85C20BE0428F32F-269546525
请求时间点：2022 10 20 18:39:07.552
<img width="1249" alt="image" src="https://user-images.githubusercontent.com/30432849/196927141-6fb87a2b-e638-45df-be4a-869a7c4da0bf.png">

**Comment by TheNorthMemory** [comment]
试着给个 '{}' body 看看？

**Comment by xy-peng** [comment]
使用的是新脚本，还是之前的老脚本？

**Comment by Memory-9527** [comment]
> 使用的是新脚本，还是之前的老脚本？

新旧脚本均存在这个问题

**Comment by xy-peng** [comment]
<img width="1205" alt="image" src="https://user-images.githubusercontent.com/1812516/197129013-4a8eee9b-f19d-4411-a943-1142f14ca73b.png">

请求body为`none`时，`request.body.raw`取到的值是`undefined`。

我修正下脚本。

**Comment by xy-peng** [comment]
@Memory-9527 public workspace 的脚本已经更新，你可以 pull changes 更新。
