### ISSUE TITLE
请教一下 为什么现在对接个扫码支付还要提供APPID呀？

### ISSUE THREAD

**Issue by luobingit** [wechatpay-apiv3/wechatpay-postman-script#17]
我只需要PC端网站的扫码支付也就是native支付功能 API响应报文显示APPID必填  意思是我必须要认证一个公众号才行嘛 
![image](https://user-images.githubusercontent.com/68454150/201469975-f715e64e-a506-4a41-a4cb-196f5e29f248.png)

**Comment by Memory-9527** [comment]
> 我只需要PC端网站的扫码支付也就是native支付功能 API响应报文显示APPID必填 意思是我必须要一个公众号才行嘛 ![图像](https://user-images.githubusercontent.com/68454150/201469975-f715e64e-a506-4a41-a4cb-196f5e29f248.png)
微信支付每个支付产品下单接口都需要有appid才可以调用，native支付下单请求中的appid参数可以使用微信服务号APPID或者小程序appid，如果不想花300块钱认证费，可以走服务商快速通道注册一个小程序来用于native支付下单使用
