### ISSUE TITLE
app支付的异步回调 怎么模拟请求呢?

### ISSUE THREAD

**Issue by feng99** [wechatpay-apiv3/wechatpay-postman-script#18]
app支付的异步回调 怎么模拟请求呢?

**Comment by xy-peng** [comment]
你是想测试自己接收回调通知的服务？能具体说说你的场景吗？

脚本不能产生真实的回调，因为签名生成要用到微信支付平台私钥，这个是不能公开的。但是可以提供一套假的证书和脚本，用postman 产生模拟的回调请求。

能满足你的需求吗？或者你觉得有什么比较好的解决方案吗？

**Comment by feng99** [comment]
您好，postman模拟可以满足的，
我要如何使用呢？
谢谢。

因为出现了json解析失败的情况，我无法模拟，自测很不方便。

**Comment by TheNorthMemory** [comment]
> 您好，postman模拟可以满足的， 我要如何使用呢？ 谢谢。
> 
> 因为出现了json解析失败的情况，我无法模拟，自测很不方便。

`json` 解析失败？ 你是不是在处理 退款回调？ 退款如果发生在「商户平台」，则以 `xml` 回调通知，非 `json`，已知问题之一。

**Comment by feng99** [comment]
不是退款，就是app支付的。

您好介绍下postman模拟支付回调那个吧
来个链接，谢谢呢。



---- 回复的原邮件 ----
| 发件人 | James ***@***.***> |
| 日期 | 2022年11月14日 13:28 |
| 收件人 | ***@***.***> |
| 抄送至 | ***@***.******@***.***> |
| 主题 | Re: [wechatpay-apiv3/wechatpay-postman-script] app支付的异步回调 怎么模拟请求呢? (Issue #18) |

您好，postman模拟可以满足的， 我要如何使用呢？ 谢谢。

因为出现了json解析失败的情况，我无法模拟，自测很不方便。

json 解析失败？ 你是不是在处理 退款回调？ 退款如果发生在「商户平台」，则以 xml 回调通知，非 json，已知问题之一。

**Comment by TheNorthMemory** [comment]
app支付分两个版本， [APIv2](https://pay.weixin.qq.com/wiki/doc/api/app/app.php?chapter=9_1) & [APIv3](https://pay.weixin.qq.com/wiki/doc/apiv3/open/pay/chapter2_5_0.shtml), 通知类型(v2->xml, v3->json)取决于你预下单使用的是哪个版本...

**Comment by feng99** [comment]
> app支付分两个版本， [APIv2](https://pay.weixin.qq.com/wiki/doc/api/app/app.php?chapter=9_1) & [APIv3](https://pay.weixin.qq.com/wiki/doc/apiv3/open/pay/chapter2_5_0.shtml), 通知类型(v2->xml, v3->json)取决于你预下单使用的是哪个版本...

您好  我使用的是v3版本的

**Comment by feng99** [comment]
> 提供一套假的证书和脚本，用postman 产生模拟的回调请求。

您好  这个如何使用呢       我在微信支付的postman接口里  未找到  app支付回调的

**Comment by xy-peng** [comment]
> 您好 这个如何使用呢 我在微信支付的postman接口里 未找到 app支付回调的

不好意思，目前还不支持。我们考虑下如何支持。

> 因为出现了json解析失败的情况，我无法模拟，自测很不方便。

JSON 解析失败是指真实的回调解析失败了？能具体说说这是什么情况吗？

**Comment by feng99** [comment]
问题已经解决了    原因是go-zero框架中   在Handler层的代码(自动生成的)httpx.Parse()函数已经读取过一次body里的值了  把这部分代码 注释就可以了
