### ISSUE TITLE
使用脚本报错

### ISSUE THREAD

**Issue by max546789** [wechatpay-apiv3/wechatpay-postman-script#2]
你好：
我使用脚本进行签名，报错了，报错信息如下：
Error | Too few bytes to parse DER.
Error | Invalid PEM formatted message.
导致无法签名！

**Comment by xy-peng** [comment]
设置私钥了吗

**Comment by max546789** [comment]
私钥有设置的

**Comment by xy-peng** [comment]
看提示是私钥不正确，请你检查下私钥复制是否完整，首尾的begin/end不要删除或重复了。

注意私钥不是`signkey`或`apiv3key`，而是文件apiclient_key.pem里包含的私钥
