### ISSUE TITLE
请问下可以支持apifox么？

### ISSUE THREAD

**Issue by qwe2539079** [wechatpay-apiv3/wechatpay-postman-script#22]
请问下可以支持apifox么？

**Comment by xy-peng** [comment]
能方便告知希望支持 Apifox 的理由吗？

我们评估过Apifox。但主要考量点在于商户密钥等敏感信息的安全。虽然 Apifox 跟 Postman 一样，提供了本地值和远程值，但是缺少 Postman 对于安全的[承诺](https://www.postman.com/trust/security/)和相关的安全功能。至少 Postman 更透明。

所以，我们目前更倾向于选用业界里长时间广泛使用的方案，即 Postman。

当然，你也可以参考 Apifox 提供的[迁移指南](https://apifox.com/blog/how-to-migrate-from-postman-to-apifox/)自己将你的工作台迁移至 Apifox。我没有试过，欢迎反馈使用体验。

**Comment by qwe2539079** [comment]
主要原因是公司中在使用Apifox这款产品，接口文档已经导入进Apifox中，但是Apifox中脚本无法使用node-forge库，导致signature无法完成。

Apifox对于敏感信息安全性确实是值得考虑的点。原则上来说，敏感信息只能存放在本地并断开跟随远程值。signature这块我再研究研究，应该有平替node-forge的其他库。

感谢您的回复。
