### ISSUE TITLE
pre-request Scripts: SyntaxError: Unexpected token '.'

### ISSUE THREAD

**Issue by zhangjianxing2011** [wechatpay-apiv3/wechatpay-postman-script#23]
There was an error in evaluating the Pre-request Script:  SyntaxError: Unexpected token '.'

<img width="1842" alt="image" src="https://github.com/wechatpay-apiv3/wechatpay-postman-script/assets/37395113/1a6cbf8a-936b-4de4-bb32-7599d684e84e">

**Comment by xy-peng** [comment]
能否提供控制台的日志？

点击窗口左下角的 `Console` 按钮，就可以看到控制台输出的日志了。

**Comment by zhangjianxing2011** [comment]
console也是一样的报错 没有更详细的信息
<img width="1916" alt="image" src="https://github.com/wechatpay-apiv3/wechatpay-postman-script/assets/37395113/c0623e7b-09c3-4b9e-a278-06d2b7acde6b">

**Comment by zhangjianxing2011** [comment]
> 能否提供控制台的日志？
> 
> 点击窗口左下角的 `Console` 按钮，就可以看到控制台输出的日志了。
console 提示也是一样的，没有更多信息
pre-request scripts 和 variables 没有去修改过

**Comment by zhangjianxing2011** [comment]
> console也是一样的报错 没有更详细的信息 <img alt="image" width="1916" src="https://user-images.githubusercontent.com/37395113/238506188-c0623e7b-09c3-4b9e-a278-06d2b7acde6b.png">



> 能否提供控制台的日志？
> 
> 点击窗口左下角的 `Console` 按钮，就可以看到控制台输出的日志了。

网页版的postman是可以的，客户端不行

**Comment by zhangjianxing2011** [comment]
> 能否提供控制台的日志？
> 
> 点击窗口左下角的 `Console` 按钮，就可以看到控制台输出的日志了。

升级了下postman可以用了 感谢

**Comment by xuegui-cao** [comment]
您好，我再调用时报了如下错误，请问是为什么？
![image](https://github.com/wechatpay-apiv3/wechatpay-postman-script/assets/133973698/540d6395-39a0-457e-8cee-2e4960e83542)
