### ISSUE TITLE
postman执行失败

### ISSUE THREAD

**Issue by zhoutou123** [wechatpay-apiv3/wechatpay-postman-script#3]
postman版本:Postman for Windows  Version 7.8.0  win32 6.1.7601 / x64,
脚本修改const private_key = "123";
const mchid = "1900009191";
const serialNo = "1DDE55AD98ED71D6EDD4A4A16996DE7B47773A8C";
执行时提示错误:There was an error in evaluating the Pre-request Script:  Error: Invalid PEM formatted message.

**Comment by xy-peng** [comment]
密钥不对，必须用申请商户证书时获得的私钥文件，参考下[这里](https://wechatpay-api.gitbook.io/wechatpay-api-v3/ren-zheng/zheng-shu#shang-hu-api-si-yao)
