### ISSUE TITLE
图片上传API无法直接使用，需要修改postman前置脚本，读取body里的meta数据

### ISSUE THREAD

**Issue by yuchenye90** [wechatpay-apiv3/wechatpay-postman-script#6]
图片上传API无法直接使用，需要修改postman前置脚本，读取body里的meta数据进行签名。可修改如下

var canonicalUrl = newUrl.getPathWithQuery();
if (method == 'POST' || method == 'PUT' || method == 'PATCH') {
    var data = pm.request.body.raw;
    if (canonicalUrl.indexOf('image-upload') >= 0) {
        var result = JSON.parse(JSON.stringify(pm.request.body.formdata)); 
        data = result[0].value;
    }
}

**Comment by xy-peng** [comment]
欢迎 pr

**Comment by sortbylist** [comment]
> 欢迎 pr

已pr。#8

**Comment by xy-peng** [comment]
@sortbylist 感谢贡献，已merge。
