### ISSUE TITLE
“商户单据号”字符串规则校验失败

### ISSUE THREAD

**Issue by qqqays** [wechatpay-apiv3/wechatpay-postman-script#7]
{
    "code": "PARAM_ERROR",
    "detail": {
        "location": "body",
        "value": "20190522_001中文11"
    },
    "message": "输入源“/body/out_request_no”映射到值字段“商户单据号”字符串规则校验失败，字符串必须匹配正则表达式“^[0-9a-zA-Z_\\-|\\*]{1,}$”"
}

**Comment by xy-peng** [comment]
错误提示是说，body字段不能有中文。报文的问题，跟脚本无关。

**Comment by qqqays** [comment]
> 错误提示是说，body字段不能有中文。报文的问题，跟脚本无关。
谢谢，已经解决
