### ISSUE TITLE
import josn script error . 

### ISSUE THREAD

**Issue by sytpb** [wechatpay-apiv3/wechatpay-postman-script#9]
![image](https://user-images.githubusercontent.com/12178686/113371977-2500fb00-939a-11eb-820b-3ec6e9378c5e.png)

**Comment by xy-peng** [comment]
请提供一下postman的版本？

**Comment by sytpb** [comment]
8.0 不行，后来升级到8.1 也是一样的。

**Comment by xy-peng** [comment]
用这个方法试试 File/+号 -> import -> raw file

**Comment by xy-peng** [comment]
我试了下，可以导入的。

方法：点击 Import 选择`Raw text`，然后输入
```
curl --location --request https://raw.githubusercontent.com/wechatpay-apiv3/wechatpay-postman-script/master/wechatpay-apiv3.postman_collection.json
```

点击Continue

**Comment by sytpb** [comment]
这试了是这样的。奇怪


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "wechatpay-apiv3/wechatpay-postman-script"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年4月2日(星期五) 中午11:25
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [wechatpay-apiv3/wechatpay-postman-script] import josn script error .  (#9)





 
我试了下，可以导入的。
 
方法：点击 Import 选择Raw text，然后输入
 curl --location --request https://raw.githubusercontent.com/wechatpay-apiv3/wechatpay-postman-script/master/wechatpay-apiv3.postman_collection.json  
点击Continue

**Comment by sytpb** [comment]
![image](https://user-images.githubusercontent.com/12178686/113378276-2ab20d00-93a9-11eb-9b1f-60811eae4edb.png)

**Comment by sytpb** [comment]
我试了用raw text  输入，但是还是报一个错，如上图。。

**Comment by xy-peng** [comment]
![image](https://user-images.githubusercontent.com/1812516/113378761-5bdf0d00-93aa-11eb-8768-d89f267fc149.png)
这样子不行？

**Comment by sytpb** [comment]
是的。我就这么干的。 复制 粘帖，continue  对吧？

**Comment by xy-peng** [comment]
输入框填curl命令，或者把下载后得到的json贴进去都可以。如果不行，看看是不是你的网关拦截了导致内容被修改了。

或者你使用的占位提示来测试下
```
curl --location --request GET http://postman-echo.com/get
```

**Comment by sytpb** [comment]
curl --location --request GET http://postman-echo.com/get   这个测试没有问题

**Comment by xy-peng** [comment]
```
curl --location --request GET https://raw.githubusercontent.com/wechatpay-apiv3/wechatpay-postman-script/master/wechatpay-apiv3.postman_collection.json
```

这样吧，可能是postman不同版本或者不同环境下使用的不同的curl版本有差别？GET是默认方法，漏掉method在我postman 8.1.0 macos上是可以的，可能你那边不行。

**Comment by sytpb** [comment]
![image](https://user-images.githubusercontent.com/12178686/113400571-965d9f80-93d4-11eb-8d9e-663560976706.png)
这个可以了，但是我的collection 里怎么是空的？

**Comment by xy-peng** [comment]
囧，我搞错了！

方法1:还是老办法，导入文件

![image](https://user-images.githubusercontent.com/1812516/113414325-51933200-93ef-11eb-8c8e-149164ace440.png)

可以看到是这样子

![image](https://user-images.githubusercontent.com/1812516/113414369-6d96d380-93ef-11eb-8377-bf08d4a882c6.png)

方法2:把整个文件复制粘贴到raw text也可以。
